In [1]:
import sys

import pandas as pd
import numpy as np
from pathlib import Path
from matplotlib_venn import venn3

import matplotlib.pyplot as plt


sys.path.append(str(Path().resolve().parent))
from utils import create_venn_diagram

In [2]:
PATH = Path("../data/raw")

files = {
    "nodes": PATH / "nodes.csv",
    "streets": PATH / "streets.csv",
    "segments": PATH / "segments.csv",
    "status": PATH / "segment_status.csv",
    "train": PATH / "train.csv"
}

# Đọc dữ liệu

In [3]:
nodes_df = pd.read_csv(files["nodes"])
streets_df = pd.read_csv(files["streets"])
segments_df = pd.read_csv(files["segments"])
status_df = pd.read_csv(files["status"])
train_df = pd.read_csv(files["train"])

# Kiểu dữ liệu

In [4]:
nodes_df.dtypes

_id       int64
long    float64
lat     float64
dtype: object

In [5]:
streets_df.dtypes

_id               int64
level             int64
max_velocity    float64
name                str
type                str
dtype: object

In [6]:
segments_df.dtypes

_id               int64
created_at          str
updated_at          str
s_node_id         int64
e_node_id         int64
length            int64
street_id         int64
max_velocity    float64
street_level      int64
street_name         str
street_type         str
dtype: object

In [7]:
status_df.dtypes

_id           int64
updated_at      str
segment_id    int64
velocity      int64
dtype: object

In [8]:
train_df.dtypes

_id               int64
segment_id        int64
date                str
weekday           int64
period              str
LOS                 str
s_node_id         int64
e_node_id         int64
length            int64
street_id         int64
max_velocity    float64
street_level      int64
street_name         str
street_type         str
long_snode      float64
lat_snode       float64
long_enode      float64
lat_enode       float64
dtype: object

# Thống kê mô tả

In [9]:
nodes_df.describe()

                _id           long            lat
count  5.779670e+05  577967.000000  577967.000000
mean   4.315269e+09     106.703700      10.808332
std    1.887984e+09       0.069665       0.049736
min    3.663672e+08     106.536005      10.676001
25%    2.964647e+09     106.655452      10.772766
50%    5.627164e+09     106.714413      10.824470
75%    5.737770e+09     106.747359      10.845259
max    6.205236e+09     106.867994      10.888998

In [10]:
streets_df.describe()

                _id        level  max_velocity
count  5.553000e+03  5553.000000    987.000000
mean   3.457455e+08     3.199712     58.232016
std    2.017849e+08     0.991818     16.046644
min    3.109679e+07     1.000000     10.000000
25%    1.991616e+08     3.000000     50.000000
50%    3.215683e+08     4.000000     60.000000
75%    5.682871e+08     4.000000     60.000000
max    6.583281e+08     4.000000    120.000000

In [11]:
segments_df.describe()

,_id,s_node_id,e_node_id,length,street_id,max_velocity,street_level
count,84633.000000,8.463300e+04,8.463300e+04,84633.000000,8.463300e+04,9871.000000,84633.000000
mean,42316.000000,3.674041e+09,3.672725e+09,41.818050,2.866904e+08,54.503596,3.500006
std,24431.587003,2.039756e+09,2.040056e+09,52.692336,2.085526e+08,16.553367,0.841222
min,0.000000,3.663672e+08,3.663672e+08,0.000000,3.109679e+07,10.000000,1.000000
25%,21158.000000,2.078951e+09,2.078951e+09,13.000000,3.511357e+07,40.000000,3.000000
50%,42316.000000,4.068031e+09,4.068031e+09,27.000000,2.517313e+08,60.000000,4.000000
75%,63474.000000,5.748273e+09,5.748270e+09,52.000000,4.693276e+08,60.000000,4.000000
max,84632.000000,6.175932e+09,6.175932e+09,1622.000000,6.583281e+08,120.000000,4.000000

In [12]:
status_df.describe()

                _id    segment_id      velocity
count  90938.000000  90938.000000  90938.000000
mean   45468.500000  40376.030009     20.754844
std    26251.683727  22415.108133     19.567112
min        0.000000     26.000000      0.000000
25%    22734.250000  21263.000000      2.000000
50%    45468.500000  41875.000000     17.000000
75%    68202.750000  58440.750000     34.000000
max    90937.000000  84535.000000    200.000000

In [13]:
train_df.describe()

,_id,segment_id,weekday,s_node_id,e_node_id,length,street_id,max_velocity,street_level,long_snode,lat_snode,long_enode,lat_enode
count,33441.000000,33441.000000,33441.000000,3.344100e+04,3.344100e+04,33441.000000,3.344100e+04,4946.000000,33441.000000,33441.000000,33441.000000,33441.000000,33441.000000
mean,16720.000000,41014.936575,2.915254,3.528928e+09,3.582345e+09,48.709010,2.715539e+08,59.299434,3.029993,106.670354,10.804326,106.670334,10.804352
std,9653.729512,22489.675329,2.329021,2.008085e+09,2.014716e+09,52.251062,1.908930e+08,14.172472,1.022137,0.041887,0.040358,0.041868,0.040377
min,0.000000,26.000000,0.000000,3.663674e+08,3.663678e+08,0.000000,3.257582e+07,10.000000,1.000000,106.537476,10.676452,106.537776,10.676467
25%,8360.000000,21967.000000,1.000000,2.079964e+09,2.079965e+09,17.000000,5.588046e+07,50.000000,2.000000,106.649521,10.772135,106.649478,10.772131
50%,16720.000000,41654.000000,3.000000,3.771416e+09,4.066314e+09,34.000000,2.420036e+08,60.000000,3.000000,106.664687,10.797884,106.664704,10.797776
75%,25080.000000,58456.000000,5.000000,5.738236e+09,5.748445e+09,63.000000,4.082464e+08,60.000000,4.000000,106.685096,10.837117,106.685212,10.837388
max,33440.000000,84535.000000,6.000000,6.175932e+09,6.175932e+09,1011.000000,6.565625e+08,120.000000,4.000000,106.867740,10.888965,106.867654,10.888993

# Kiểm tra dữ liệu thừa thiếu

## nodes.csv

In [14]:
print(nodes_df.duplicated().sum())
nodes_df.isnull().sum()

0

_id     0
long    0
lat     0
dtype: int64

## streets.csv

In [15]:
print(streets_df.duplicated().sum())
streets_df.isnull().sum()

0

_id                0
level              0
max_velocity    4566
name            1605
type               0
dtype: int64

In [16]:
# Thế max_velocity = -1 cho giá trị bị thiếu
streets_df["max_velocity"] = streets_df["max_velocity"].fillna(-1)

In [17]:
# Thế name = "None" cho giá trị bị thiếu
streets_df["name"] = streets_df["name"].fillna("None")

In [18]:
streets_df.isnull().sum()

_id             0
level           0
max_velocity    0
name            0
type            0
dtype: int64

## segments.csv

In [19]:
print(segments_df.duplicated().sum())
segments_df.isnull().sum()

0

_id                 0
created_at          0
updated_at          0
s_node_id           0
e_node_id           0
length              0
street_id           0
max_velocity    74762
street_level        0
street_name       152
street_type         0
dtype: int64

In [20]:
segments_df["max_velocity"] = segments_df["max_velocity"].fillna(-1)

In [21]:
segments_df["street_name"] = segments_df["street_name"].fillna("None")

In [22]:
segments_df.isnull().sum()

_id             0
created_at      0
updated_at      0
s_node_id       0
e_node_id       0
length          0
street_id       0
max_velocity    0
street_level    0
street_name     0
street_type     0
dtype: int64

## segment_status.csv

In [23]:
print(status_df.duplicated().sum())
status_df.isnull().sum()

0

_id           0
updated_at    0
segment_id    0
velocity      0
dtype: int64

## train.csv

In [24]:
print(train_df.duplicated().sum())
train_df.isnull().sum()

0

_id                 0
segment_id          0
date                0
weekday             0
period              0
LOS                 0
s_node_id           0
e_node_id           0
length              0
street_id           0
max_velocity    28495
street_level        0
street_name         1
street_type         0
long_snode          0
lat_snode           0
long_enode          0
lat_enode           0
dtype: int64

In [25]:
train_df["max_velocity"] = train_df["max_velocity"].fillna(-1)

In [26]:
train_df["street_name"] = train_df["street_name"].fillna("None")

In [27]:
train_df.isnull().sum()

_id             0
segment_id      0
date            0
weekday         0
period          0
LOS             0
s_node_id       0
e_node_id       0
length          0
street_id       0
max_velocity    0
street_level    0
street_name     0
street_type     0
long_snode      0
lat_snode       0
long_enode      0
lat_enode       0
dtype: int64

# Kiểm tra tính nhất quán của dữ liệu

## Node

### Node trong nodes.csv

In [28]:
# Đảm bảo rằng _id là thuộc tính duy nhất
print("Số lượng id không bị trùng:", nodes_df["_id"].duplicated().sum())
nodes = set(nodes_df["_id"]) # Tập các nút
n_nodes = len(nodes)
print("Số lượng nút có trong nodes.csv:", n_nodes)

Số lượng id không bị trùng: 0
Số lượng nút có trong nodes.csv: 577967

### Node trong segment

#### s_node_id

In [29]:
s_segments_nodes = set(segments_df["s_node_id"])
n_s_segments_nodes = len(s_segments_nodes)
print("Số lượng nút đầu của segment:", n_s_segments_nodes)

inter_s_nodes_segments = nodes & s_segments_nodes
print("Số lượng e_node giao với node:", len(inter_s_nodes_segments))

Số lượng nút đầu của segment: 52384
Số lượng e_node giao với node: 52384

Do $\pi_{\_id}(nodes) \cap \pi_{s\_node\_id}(segments) = \pi_{s\_node\_id}(segments)$<br>
$\Rightarrow \pi_{\_id}(segments) \subset \pi_{s\_node\_id}(nodes)$

#### e_node_id

In [30]:
e_segments_nodes = set(segments_df["e_node_id"])
n_e_segments_nodes = len(e_segments_nodes)
print("Số lượng nút đích của segment:", n_e_segments_nodes)

inter_e_nodes_segments = nodes & e_segments_nodes
print("Số lượng e_node giao với node:", len(inter_e_nodes_segments))

Số lượng nút đích của segment: 52386
Số lượng e_node giao với node: 52386

Do $\pi_{\_id}(nodes) \cap \pi_{e\_node\_id}(segments) = \pi_{e\_node\_id}(segments)$<br>
$\Rightarrow \pi_{\_id}(segments) \subset \pi_{e\_node\_id}(nodes)$

#### Tập giao giữa s_node và e_nocde

In [31]:
inter_s_e_segment_nodes = s_segments_nodes & e_segments_nodes
print("Số lượng node chung của train:", len(inter_s_e_segment_nodes))

Số lượng node chung của train: 52345

### Node trong train

#### s_node_id

In [32]:
s_train_nodes = set(train_df["s_node_id"])
n_s_train_nodes = len(s_train_nodes)
print("Số lượng nút đầu của train:", n_s_train_nodes)

inter_s_nodes_train = nodes & s_train_nodes
print("Số lượng e_node giao với node:", len(inter_s_nodes_train))

Số lượng nút đầu của train: 8430
Số lượng e_node giao với node: 8430

#### e_node_id

In [33]:
e_train_nodes = set(train_df["e_node_id"])
n_e_train_nodes = len(e_train_nodes)
print("Số lượng nút đầu của train:", n_e_train_nodes)

inter_e_nodes_train = nodes & e_train_nodes
print("Số lượng e_node giao với node:", len(inter_e_nodes_train))

Số lượng nút đầu của train: 8427
Số lượng e_node giao với node: 8427

#### Tập giao giữa s_node và e_node

In [34]:
inter_s_e_train_nodes = s_train_nodes & e_train_nodes
print("Số lượng node chung của train:", len(inter_s_e_train_nodes))

Số lượng node chung của train: 5543

### Mối quan hệ của node trong segments.csv và train.csv

In [35]:
# Tập giao nút nguồn của segments và train
inter_s_segments_train_nodes = s_segments_nodes & s_train_nodes
print("Số lượng s_node của segments giao với train:", len(inter_s_segments_train_nodes))

Số lượng s_node của segments giao với train: 8430

In [36]:
# Tập giao nút đích của segments và train
inter_e_segments_train_nodes = e_segments_nodes & e_train_nodes
print("Số lượng s_node của segments giao với train:", len(inter_e_segments_train_nodes))

Số lượng s_node của segments giao với train: 8427

$\pi_{s\_node\_id}(segments) \cap \pi_{s\_node\_id}(train) = \pi_{s\_node\_id}(train)$<br>
$\Rightarrow \pi_{s\_node\_id}(train) \subset \pi_{s\_node\_id}(segments) \subset \pi_{\_id}(nodes)$<br>

$\pi_{e\_node\_id}(segments) \cap \pi_{e\_node\_id}(train) = \pi_{e\_node\_id}(train)$<br>
$\Rightarrow \pi_{e\_node\_id}(train) \subset \pi_{e\_node\_id}(segments) \subset \pi_{\_id}(nodes)$

## Street

### Street trong streets.csv

In [37]:
# Đảm bảo _id trong street là duy nhất
print("Số lượng _id bị trùng:", streets_df["_id"].duplicated().sum())
streets = set(streets_df["_id"])
n_streets = len(streets)
print("Số lượng street trong streets.csv:", n_streets)

Số lượng _id bị trùng: 0
Số lượng street trong streets.csv: 5553

### Street trong segments.csv

In [38]:
segments_streets = set(segments_df["street_id"])
n_segments_streets = len(segments_streets)
print("Số lượng street có trong segments.csv:", n_segments_streets)

inter_streets_segments = streets & segments_streets
print("Số lượng street trong tập giao streets.csv và segments.csv:", len(inter_streets_segments))

Số lượng street có trong segments.csv: 5539
Số lượng street trong tập giao streets.csv và segments.csv: 5539

$\pi_{\_id}(streets) \cap \pi_{street\_id}(segments)=\pi_{street\_id}(segments)$<br>
$\Rightarrow \pi_{street\_id}(segments) \subset \pi_{\_id}(streets)$

### Street trong train.csv

In [39]:
train_streets = set(train_df["street_id"])
n_train_streets = len(train_streets)
print("Số lượng street có trong train.csv:", n_train_streets)

inter_streets_train = streets & train_streets
print("Số lượng street có trong tập giao streets.csv và train.csv:", len(inter_streets_train))

Số lượng street có trong train.csv: 1967
Số lượng street có trong tập giao streets.csv và train.csv: 1967

$\pi_{\_id}(streets) \cap \pi_{street\_id}(train)=\pi_{street\_id}(train)$<br>
$\Rightarrow \pi_{street\_id}(train) \subset \pi_{\_id}(streets)$

### Mối quan hệ của street trong segments.csv và train.csv

In [40]:
inter_segments_train_streets = segments_streets & train_streets
print("Số lượng street trong tập giao của segments.csv và train.csv:", len(inter_segments_train_streets))

Số lượng street trong tập giao của segments.csv và train.csv: 1967

$\pi_{street\_id}(segments) \cap \pi_{street\_id}(train) = \pi_{street\_id}(train)$<br>
$\Rightarrow \pi_{street\_id}(train) \subset \pi_{street\_id}(segments) \subset \pi_{\_id}(streets)$

## Segment

### Segment trong segments.csv

In [41]:
# Đảm bảo _id của segments là khóa chính
print("Số lượng _id bị trùng:", segments_df["_id"].duplicated().sum())
segments = set(segments_df["_id"])
n_segments = len(segments)
print("Số lượng segments trong segments.csv:", n_segments)

Số lượng _id bị trùng: 0
Số lượng segments trong segments.csv: 84633

### Segment trong segment_status.csv

In [42]:
status_segments = set(status_df["segment_id"])
n_status_segments = len(status_segments)
print("Số lượng segments có trong status_segments:", n_status_segments)

inter_segment_status = segments & status_segments
print("Số lượng segments trong segments.csv giao với status_segments.csv:", len(inter_segment_status))

Số lượng segments có trong status_segments: 10027
Số lượng segments trong segments.csv giao với status_segments.csv: 10027

$\pi_{\_id}(segments) \cap \pi_{segment\_id}(segment\_status) = \pi_{segment\_id}(segment\_status)$<br>
$\Rightarrow \pi_{segment\_id}(segment\_status) \subset \pi_{\_id}(segments)$

### Segment trong train.csv

In [43]:
train_segments = set(train_df["segment_id"])
n_train_segments = len(train_segments)
print("Số lượng segments có trong train.csv:", n_train_segments)

inter_segment_train = segments & train_segments
print("Số lượng segments trong segments.csv giao với segment_status.csv:", len(inter_segment_train))

Số lượng segments có trong train.csv: 10027
Số lượng segments trong segments.csv giao với segment_status.csv: 10027

$\pi_{\_id}(segments) \cap \pi_{segment\_id}(train) = \pi_{segment\_id}(train)$<br>
$\Rightarrow \pi_{segment\_id}(train) \subset \pi_{\_id}(segments)$

### Mối quan hệ của segment trong segments_status.csv và train.csv

In [44]:
inter_status_train_segments = status_segments & train_segments
print(len(inter_status_train_segments))

10027

$
\Rightarrow \pi_{segment\_id}(train) = \pi_{segment\_id}(segment\_status) \subset \pi_{\_id}(segments)
$

## Tập các thuộc tính

### Street trong streets.csv và segments.csv

In [45]:
street_filtered_streets = set(
    streets_df[["_id", "name", "level", "max_velocity", "type"]]
    .apply(tuple, axis=1)
)
street_filtered_segments = set(
    segments_df[["street_id", "street_name", "street_level", "max_velocity", "street_type"]]
    .apply(tuple, axis=1)
)

inter_street_filtered_streets_segments = street_filtered_streets & street_filtered_segments
print("Số phần tử của tập streets của segments.csv:", len(street_filtered_segments))
print("Số phần tử của tập streets của streets.csv:", len(street_filtered_streets))
print("Số phần tử của tập giao:", len(inter_street_filtered_streets_segments))

Số phần tử của tập streets của segments.csv: 6301
Số phần tử của tập streets của streets.csv: 5553
Số phần tử của tập giao: 3954

In [46]:
# streets(...) \ segments(...)
_street_streets_segments = street_filtered_streets - street_filtered_segments
print(len(_street_streets_segments))

_street_segments_streets = street_filtered_segments - street_filtered_streets
print(len(_street_segments_streets))

1599
2347

Do $|\pi_{\_id, name, level, max\_velocity, type}(streets) \cap \pi_{street\_id, street\_name, street\_type, max\_velocity, street\_type}(segments) \not = |\pi_{\_id, name, level, max\_velocity, type}(streets)|$
Và $|\pi_{\_id, name, level, max\_velocity, type}(streets) \cap \pi_{street\_id, street\_name, street\_type, max\_velocity, street\_type}(segments) \not = |\pi_{street\_id, street\_name, street\_type, max\_velocity, street\_type}(segments)|$
Nên cả hai đều không phải là tập cha hay tập con của nhau

#### Kiểm tra từng thuộc tính

##### Kiểm tra tập thuộc tính level

In [47]:
street_filtered_level_streets = set(streets_df[["_id", "level"]].apply(tuple, axis=1))
street_filtered_level_segments = set(segments_df[["street_id", "street_level"]].apply(tuple, axis=1))

inter_street_level_filtered_streets_segments = (
    street_filtered_level_streets & 
    street_filtered_level_segments
)

print("Số phần tử của tập streets của segments.csv:", len(street_filtered_level_segments))
print("Số phần tử của tập streets của streets.csv:", len(street_filtered_level_streets))
print("Số phần tử của tập giao:", len(inter_street_level_filtered_streets_segments))

Số phần tử của tập streets của segments.csv: 5539
Số phần tử của tập streets của streets.csv: 5553
Số phần tử của tập giao: 5539

##### Kiểm tra tập thuộc tính max_velocity

In [48]:
street_filtered_max_velocity_streets = set(streets_df[["_id", "max_velocity"]].apply(tuple, axis=1))
street_filtered_max_velocity_segments = set(segments_df[["street_id", "max_velocity"]].apply(tuple, axis=1))

inter_street_max_velocity_filtered_streets_segments = (
    street_filtered_max_velocity_streets & 
    street_filtered_max_velocity_segments
)

print("Số phần tử của tập streets của segments.csv:", len(street_filtered_max_velocity_segments))
print("Số phần tử của tập streets của streets.csv:", len(street_filtered_max_velocity_streets))
print("Số phần tử của tập giao:", len(inter_street_max_velocity_filtered_streets_segments))

Số phần tử của tập streets của segments.csv: 5539
Số phần tử của tập streets của streets.csv: 5553
Số phần tử của tập giao: 5539

##### Kiểm tra tập thuộc tính type

In [49]:
street_filtered_type_streets = set(streets_df[["_id", "type"]].apply(tuple, axis=1))
street_filtered_type_segments = set(segments_df[["street_id", "street_type"]].apply(tuple, axis=1))

inter_street_type_filtered_streets_segments = (
    street_filtered_type_streets & 
    street_filtered_type_segments
)
print("Số phần tử của tập streets của segments.csv:", len(street_filtered_type_segments))
print("Số phần tử của tập streets của streets.csv:", len(street_filtered_type_streets))
print("Số phần tử của tập giao:", len(inter_street_type_filtered_streets_segments))

Số phần tử của tập streets của segments.csv: 5816
Số phần tử của tập streets của streets.csv: 5553
Số phần tử của tập giao: 5422

##### Kiểm tra thuộc tính name

In [50]:
street_filtered_name_streets = set(streets_df[["_id", "name"]].apply(tuple, axis=1))
street_filtered_name_segments = set(segments_df[["street_id", "street_name"]].apply(tuple, axis=1))

inter_street_type_filtered_streets_segments = (
    street_filtered_name_streets & 
    street_filtered_name_segments
)
print("Số phần tử của tập streets của segments.csv:", len(street_filtered_name_segments))
print("Số phần tử của tập streets của streets.csv:", len(street_filtered_name_streets))
print("Số phần tử của tập giao:", len(inter_street_type_filtered_streets_segments))

Số phần tử của tập streets của segments.csv: 6103
Số phần tử của tập streets của streets.csv: 5553
Số phần tử của tập giao: 3954

Như vậy tập các thuộc tính của streets bị thiếu nhất quán ở thuộc tính **type** và **name**

#### Phân tích tập thuộc tính

##### Thuộc tính type

In [51]:
# segments.csv
unique_segments_type = np.sort(segments_df["street_type"].unique())
n_unique_segments_type = len(unique_segments_type)

# streets.csv
unique_train_type = np.sort(streets_df["type"].unique())
n_unique_train_type = len(unique_train_type)

print("Số unique các loại đường trong segments.csv:", n_unique_segments_type)
print("Số unique các loại đường trong train.csv:", n_unique_train_type)

Số unique các loại đường trong segments.csv: 53
Số unique các loại đường trong train.csv: 11

In [52]:
print(unique_segments_type)
print(unique_train_type)

['apartments' 'atm' 'bank' 'bridge' 'bus_station' 'bus_stop' 'car'
 'chalet' 'church' 'cinema' 'clothes' 'college' 'community_centre'
 'company' 'construction' 'convenience' 'dentist' 'department_store'
 'dormitory' 'dry_cleaning' 'fast_food' 'fire_station' 'fuel' 'government'
 'hospital' 'hostel' 'house' 'industrial' 'marketplace' 'motorway'
 'motorway_link' 'pedestrian' 'pitch' 'police' 'primary' 'primary_link'
 'residential' 'restaurant' 'school' 'secondary' 'secondary_link'
 'service' 'shelter' 'swimming_pool' 'tertiary' 'tertiary_link'
 'theme_park' 'training_area' 'trunk' 'trunk_link' 'unclassified'
 'university' 'yes']
['motorway' 'motorway_link' 'primary' 'primary_link' 'secondary'
 'secondary_link' 'tertiary' 'tertiary_link' 'trunk' 'trunk_link'
 'unclassified']

Như vậy thuộc tính "street_id" của tập dữ liệu segements.csv và streets.csv hoàn toàn khác.
Trong khi segments thể hiện loại công trình thì streets.csv thể hiện loại công trình giao thông.

##### Thuộc tính name

In [53]:
# segments.csv
unique_segments_name = set(segments_df["street_name"].unique())
n_unique_segments_name = len(unique_segments_name)

# streets.csv
unique_streets_name = set(streets_df["name"].unique())
n_unique_streets_name = len(unique_streets_name)

print("Số unique các loại đường trong segments.csv:", n_unique_segments_name)
print("Số unique các loại đường trong streets.csv:", n_unique_streets_name)

Số unique các loại đường trong segments.csv: 1389
Số unique các loại đường trong streets.csv: 1049

In [54]:
# Tên các đường không trùng khớp
# Có trong segments.csv
_street_segments_streets = street_filtered_name_segments - street_filtered_name_streets

# Có trong train.csv
_street_streets_segments = street_filtered_name_streets - street_filtered_name_segments

print("|street_id, street_name (segments) - _id, name (streets)|", len(_street_segments_streets))
print("|_id, name (streets) - |street_id, street_name (segments)|", len(_street_streets_segments))

|street_id, street_name (segments) - _id, name (streets)| 2149
|_id, name (streets) - |street_id, street_name (segments)| 1599

In [55]:
# In một phần đường có trong segments
for idx, value in enumerate(_street_segments_streets):
    print(value)
    if idx == 9:
        break

(610072097, 'Đường Lũy Bán Bích')
(605485390, 'Phường Bình Chiểu')
(568236970, 'Phường Bến Nghé')
(604502171, 'Tân Kỳ Tân Quý')
(404516660, 'Phạm Văn Đồng')
(397354320, 'Quốc lộ 1A')
(315658247, 'Thành phố Thuận An')
(215037911, 'Lê Trọng Tấn')
(503282433, 'Phường Hiệp Bình Phước')
(566581410, 'Xa Lộ Hà Nội')

In [56]:
# In ra thử các đoạn đường được đặt tên có trong streets
count = 0
for idx, value in enumerate(_street_streets_segments):
    if value[1] == "None":
        continue
    print(value)
    count+=1

(604839608, 'Đường Vành đai ĐHQG')
(32577339, 'Trần Khắc Chân')
(315658210, 'Cầu Phú Long')
(315658194, 'Cầu Phú Long')
(605436178, 'Đường số 18')
(32576381, 'Nguyễn Bình')
(264100066, 'Tân Long')

### Street trong street.csv và train.csv

In [57]:
# Tập streets có ở trên tái sử dụng
street_filtered_train = set(
    train_df[["street_id", "street_name", "street_level", "max_velocity", "street_type"]]
    .apply(tuple, axis=1)
)

inter_street_streets_train = street_filtered_streets & street_filtered_train
print("Số phần tử của tập streets của train.csv:", len(street_filtered_train))
print("Số phần tử của tập streets của streets.csv:", len(street_filtered_streets))
print("Số phần tử của tập giao:", len(inter_street_streets_train))

Số phần tử của tập streets của train.csv: 2031
Số phần tử của tập streets của streets.csv: 5553
Số phần tử của tập giao: 1552

### Street trong train.csv và segments.csv

In [58]:
# Tập streets có ở trên tái sử dụng
inter_street_train_segments = street_filtered_train & street_filtered_segments
print("Số phần tử của tập streets của train.csv:", len(street_filtered_train))
print("Số phần tử của tập streets của segments.csv:", len(street_filtered_segments))
print("Số phần tử của tập giao:", len(inter_street_train_segments))

Số phần tử của tập streets của train.csv: 2031
Số phần tử của tập streets của segments.csv: 6301
Số phần tử của tập giao: 2031

Như vậy $\pi_{street\_id, street\_name, street\_level, max\_velocity, street\_type}(train) \subset \pi_{street\_id, street\_name, street\_level, max\_velocity, street\_type}(segments) \not \subset \pi_{\_id, name, level, max\_velocity, type}(streets)$

Vì tập _id của streets là tập cha của segments, có nghĩa là có thể tập các thuộc tính không đồng bộ với _id

### Kiểm tra sự mẫu thuẫn của street trong segments và streets

In [124]:
temp_streets_df = streets_df[["_id", "name"]].copy()
temp_streets_df.head()

        _id            name
0  31096786       Quốc Lộ 1
1  32575737            None
2  32575794      Chu Văn An
3  32575820   Nguyễn Văn Bá
4  32575823  Nguyễn Thị Nhỏ

In [125]:
temp_segments_df = segments_df[["street_id", "street_name"]].copy()
temp_segments_df = temp_segments_df.rename(
    columns={
        "street_id": "_id",
        "street_name": "name",
        "street_level": "level",
        "street_type": "type"
})
temp_segments_df.head()

        _id       name
0  31096786  Quốc Lộ 1
1  31096786  Quốc Lộ 1
2  31096786  Quốc Lộ 1
3  31096786  Quốc Lộ 1
4  31096786  Quốc Lộ 1

In [108]:
temp_streets_df.duplicated().sum()

np.int64(0)

In [109]:
temp_segments_df.duplicated().sum()

np.int64(0)

In [110]:
temp_segments_df.duplicated().sum()

np.int64(0)

In [111]:
conflicts_df = pd.concat([temp_streets_df, temp_segments_df]).drop_duplicates()
group_id_conflicts = conflicts_df.groupby("_id")

In [117]:
print(len(conflicts_df))

7900

In [114]:
count = 0

for _id, group in conflicts_df.groupby('_id'):
    if count == 4:
        break
    if len(group) > 1:
        print(f"\n=== ID: {_id}  |  Conflicts: {len(group)} ===")
        print(group.to_string(index=False))
        print("-" * 80)
        count += 1

=== ID: 32575737  |  Conflicts: 3 ===
     _id           name  level  max_velocity         type
32575737           None      4          -1.0 unclassified
32575737     Thương Mại      4          -1.0  marketplace
32575737 Xã Trung Chánh      4          -1.0 unclassified
--------------------------------------------------------------------------------

=== ID: 32575874  |  Conflicts: 2 ===
     _id           name  level  max_velocity         type
32575874           None      4          -1.0 unclassified
32575874 Xã Trung Chánh      4          -1.0 unclassified
--------------------------------------------------------------------------------

=== ID: 32576095  |  Conflicts: 3 ===
     _id               name  level  max_velocity     type
32576095               None      4          -1.0 tertiary
32576095 đường Thái Thị Giữ      4          -1.0 tertiary
32576095         Xã Bà Điểm      4          -1.0 tertiary
--------------------------------------------------------------------------------

=== ID: 32577094  |  Conflicts: 2 ===
     _id             name  level  max_velocity     type
32577094             None      4          -1.0 tertiary
32577094 Phường Thảo Điền      4          -1.0 tertiary
--------------------------------------------------------------------------------

In [123]:
count = 0
for _id, group in conflicts_df.groupby('_id'):
    if count == 4:
        break
    
    if len(group) > 1:                                   # has conflicts
        # Check if "None" exists anywhere in the group
        if (group["name"] != "None").all():              # All names are NOT "None"
            print(f"\n=== ID: {_id} | Conflicts: {len(group)} ===")
            print(group[["_id", "name"]].to_string(index=False))
            print("-" * 80)
            count += 1

Như vậy sẽ có 2 trường hợp:
- TH1: Con đường không mang tên trong streets nhưng lại được đặt tên trong segments chỉ có một tên.
- TH2: Con đường không mang tên trong streets nhưng lại được đặt tên trong segments và có nhiều tên.

Giải pháp: Đặt tên đường trong streets bằng tên trong segments. Trong trường hợp có nhiều tên thì thêm id riêng.

## Tính nhất quán của tập các thuộc tính segments và streets

### s_node_id, e_node_id

In [ ]:
node_filtered_train = set(train_df[["segment_id", "s_node_id", "e_node_id"]].apply(tuple, axis=1))
node_filtered_segments = set(segments_df[["_id", "s_node_id", "e_node_id"]].apply(tuple, axis=1))

inter_node_filtered_train_segments = node_filtered_train & node_filtered_segments
print("Số phần tử sau khi lọc của tập train:", len(node_filtered_train))
print("Số phần tử sau khi lọc tập segments:", len(node_filtered_segments))
print("Số phần tử của tập giao:", len(inter_node_filtered_train_segments))

$\Rightarrow \pi_{segment\_id, s\_node\_id, e\_node\_id}(train) \subset \pi_{\_id, s\_node\_id, e\_node\_id}(segments)$<br>
Có thể loại bỏ thuộc tính s_node_id, e_node_id trong train

### long_snode, lat_snode, long_enode, lat_enode

In [ ]:
nodes_tuple_set = set(nodes_df.apply(tuple, axis=1))

In [ ]:
# snode
snode_loc_filtered_train = set(train_df[["s_node_id", "long_snode", "lat_snode"]].apply(tuple, axis=1))
inter_snode_loc_train_nodes = nodes_tuple_set & snode_loc_filtered_train
print("Số node của nodes.csv:", len(nodes_tuple_set))
print("Số phần tử tập snode loc của train:", len(inter_snode_loc_train_nodes))
print("Số phần tử tập giao snode loc của train và nodes:", len(inter_snode_loc_train_nodes))

In [ ]:
# enode
enode_loc_filtered_train = set(train_df[["e_node_id", "long_enode", "lat_enode"]].apply(tuple, axis=1))
inter_enode_loc_train_nodes = nodes_tuple_set & enode_loc_filtered_train
print("Số node của nodes.csv:", len(nodes_tuple_set))
print("Số phần tử tập enode loc của train:", len(inter_enode_loc_train_nodes))
print("Số phần tử tập giao enode loc của train và nodes:", len(inter_enode_loc_train_nodes))

In [ ]:
train_df.columns

In [ ]:
segments_df.columns