In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
PATH = Path("../data/preprocess")

files = {
    "nodes": PATH / "nodes.csv",
    "streets": PATH / "streets.csv",
    "segments": PATH / "segments.csv",
    "status": PATH / "segment_status.csv",
    "train": PATH / "train.csv"
}

In [3]:
nodes_df = pd.read_csv(files["nodes"])
streets_df = pd.read_csv(files["streets"])
segments_df = pd.read_csv(files["segments"])
status_df = pd.read_csv(files["status"])
train_df = pd.read_csv(files["train"])

In [4]:
segments_df["created_at"] = pd.to_datetime(segments_df["created_at"])
segments_df["updated_at"] = pd.to_datetime(segments_df["updated_at"])
status_df["updated_at"] = pd.to_datetime(status_df["updated_at"])

# Phân tích từng thuộc tính

## Nodes

In [5]:
nodes_df.shape

(577967, 3)

In [6]:
nodes_df.head()

         _id        long        lat
0  366367223  106.629056  10.804243
1  366367233  106.709701  10.771110
2  366367242  106.737189  10.709337
3  366367274  106.760081  10.854489
4  366367285  106.721163  10.804994

In [7]:
nodes_df.shape

(577967, 3)

## Segments

In [8]:
segments_df.shape

(84633, 8)

In [9]:
segments_df.head()

,_id,created_at,updated_at,s_node_id,e_node_id,length,street_id,type
0,0,2020-10-18 13:26:17.365000+00:00,2020-10-18 13:26:17.365000+00:00,373543511,5468660805,0.0114,31096786,trunk
1,1,2020-10-18 13:26:17.400000+00:00,2020-10-18 13:26:17.400000+00:00,5468660805,5738158916,0.0009,31096786,trunk
2,2,2020-10-18 13:26:17.435000+00:00,2020-10-18 13:26:17.435000+00:00,5738158916,5738158918,0.0023,31096786,trunk
3,3,2020-10-18 13:26:17.444000+00:00,2020-10-18 13:26:17.444000+00:00,5738158918,5738158912,0.0066,31096786,trunk
4,4,2020-10-18 13:26:17.452000+00:00,2020-10-18 13:26:17.452000+00:00,5738158912,5758104203,0.0127,31096786,trunk

In [10]:
segments_df[segments_df["created_at"] != segments_df["updated_at"]]

,_id,created_at,updated_at,s_node_id,e_node_id,length,street_id,type
10,10,2020-10-18 13:26:17.486000+00:00,2021-04-04 09:04:01.778000+00:00,366459052,5764885888,0.0108,32575737,marketplace
11,11,2020-10-18 13:26:17.491000+00:00,2021-04-04 09:04:03.289000+00:00,5764885888,366459052,0.0108,658328102,unclassified
147,147,2020-10-18 13:26:18.318000+00:00,2021-04-04 09:04:04.709000+00:00,366465467,366466938,0.0011,32575874,unclassified
148,148,2020-10-18 13:26:18.321000+00:00,2021-04-04 09:04:06.037000+00:00,366466938,366465467,0.0011,32575874,unclassified
149,149,2020-10-18 13:26:18.325000+00:00,2021-04-04 09:04:07.286000+00:00,366466938,366416812,0.0021,32575874,unclassified
...,...,...,...,...,...,...,...,...
84614,84614,2020-10-18 13:30:29.756000+00:00,2021-04-04 17:00:38.398000+00:00,6152609247,6152609246,0.0020,656851094,unclassified
84615,84615,2020-10-18 13:30:29.758000+00:00,2021-04-04 17:00:41+00:00,6152609247,6152609248,0.0074,656851094,unclassified
84616,84616,2020-10-18 13:30:29.761000+00:00,2021-04-04 17:00:42.910000+00:00,6152609248,6152609247,0.0074,656851094,unclassified
84617,84617,2020-10-18 13:30:29.764000+00:00,2021-04-04 17:00:45.184000+00:00,6152609248,6152609249,0.0010,656851094,residential
84618,84618,2020-10-18 13:30:29.766000+00:00,2021-04-04 17:00:46.926000+00:00,6152609249,6152609248,0.0010,656851094,residential

In [11]:
(segments_df["created_at"] - segments_df["updated_at"]).mean()

Timedelta('-39 days +21:15:02.092025')

In [12]:
segments_df["type"].unique()

<ArrowStringArray>
[           'trunk',      'marketplace',     'unclassified',
         'tertiary',        'secondary',     'primary_link',
          'primary',      'bus_station',             'bank',
      'residential',             'fuel', 'department_store',
       'trunk_link',       'theme_park',    'tertiary_link',
   'secondary_link',           'bridge',       'apartments',
           'hostel',     'fire_station',      'convenience',
          'shelter',    'training_area',       'pedestrian',
     'dry_cleaning',    'motorway_link',           'chalet',
         'motorway',            'pitch',       'industrial',
        'dormitory',       'university',         'bus_stop',
          'service',              'car',            'house',
          'company',           'school',          'college',
     'construction',       'restaurant',         'hospital',
              'yes',       'government',          'clothes',
          'dentist',              'atm',        'fast_food',
    'swimming_pool',           'police',           'church',
           'cinema', 'community_centre']
Length: 53, dtype: str

## Segment_status

In [13]:
status_df.shape

(90938, 4)

## Streets

In [14]:
streets_df.shape

(6312, 5)

## Train

In [15]:
train_df.head()

   _id  segment_id        date  weekday        period LOS
0    0          26  2021-04-16        4   period_0_30   A
1    1          33  2020-08-02        6  period_23_30   C
2    2          33  2020-08-03        0   period_0_00   D
3    3          67  2021-03-09        1   period_9_30   B
4    4          67  2021-03-23        1   period_9_30   B

In [16]:
train_df.shape

(33441, 6)

In [17]:
status_df[status_df["segment_id"] == 26]

         _id                       updated_at  segment_id  velocity
89252  89252 2021-04-16 00:55:31.333000+00:00          26       117

# Kiểm tra tính nhất quán train với status

$|\pi_{segment\_id, date}(train) \cap \pi_{segment\_id, DATE(updated\_at)}(segment\_status)|= x$, 
$x\in \{|\pi_{segment\_id, date}(train)|, |\pi_{segment\_id, DATE(updated\_at)}(segment\_status)|\}$

$|\pi_{segment\_id, date}(train) \cap \pi_{segment\_id, FLOOR(updated\_at, 30m)}(segment\_status)|= y$, 
$x\in \{|\pi_{segment\_id, date}(train)|, |\pi_{segment\_id, FLOOR(updated\_at, 30m)}(segment\_status)|\}$

In [18]:
status_df["time_bucket"] = status_df["updated_at"].dt.floor("30min")

In [19]:
status_df["period"] = (
    "period_" +
    status_df["time_bucket"].dt.hour.astype(str) + "_" +
    status_df["time_bucket"].dt.strftime("%M")
)

In [20]:
status_df["date"] = status_df["updated_at"].dt.strftime("%Y-%m-%d")

In [21]:
train_date = set(train_df[["segment_id", "date"]].apply(tuple, axis=1))
status_date = set(status_df[["segment_id", "date"]].apply(tuple, axis=1))

In [22]:
train_date = set(train_df[["segment_id", "date"]].apply(tuple, axis=1))
status_date = set(status_df[["segment_id", "date"]].apply(tuple, axis=1))

inter_train_status_date = train_date & status_date
print("Tập date trong train:", len(train_date))
print("Tập date trong status:", len(status_date))
print("Tập giao:", len(inter_train_status_date))

Tập date trong train: 25024
Tập date trong status: 25024
Tập giao: 25024

In [23]:
train_period = set(train_df[["segment_id", "period"]].apply(tuple, axis=1))
status_period = set(status_df[["segment_id", "period"]].apply(tuple, axis=1))

inter_train_status_period = train_period & status_period
print("Tập date trong train:", len(train_period))
print("Tập date trong status:", len(status_period))
print("Tập giao:", len(inter_train_status_period))

Tập date trong train: 27772
Tập date trong status: 27772
Tập giao: 27772

In [24]:
_train_status_period = train_period - status_period

for idx, v in enumerate(_train_status_period):
    if idx == 4:
        break
    print(v)

In [25]:
train_df[train_df["segment_id"] == 70339]

         _id  segment_id        date  weekday       period LOS
30226  30226       70339  2020-09-11        4  period_0_00   A

In [26]:
status_df[status_df["segment_id"] == 70339]

,_id,updated_at,segment_id,velocity,time_bucket,period,date
38126,38126,2020-09-11 00:15:56.353000+00:00,70339,39,2020-09-11 00:00:00+00:00,period_0_00,2020-09-11

 # Xây dựng tập dữ liệu dựa trên train

In [27]:
train_df.columns

Index(['_id', 'segment_id', 'date', 'weekday', 'period', 'LOS'], dtype='str')

In [28]:
merged_df = train_df.merge(
    status_df,
    on=["segment_id", "period", "date"],
    how="inner"
)

In [29]:
merged_df

,_id_x,segment_id,date,weekday,period,LOS,_id_y,updated_at,velocity,time_bucket
0,0,26,2021-04-16,4,period_0_30,A,89252,2021-04-16 00:55:31.333000+00:00,117,2021-04-16 00:30:00+00:00
1,1,33,2020-08-02,6,period_23_30,C,892,2020-08-02 23:56:28.019000+00:00,34,2020-08-02 23:30:00+00:00
2,1,33,2020-08-02,6,period_23_30,C,4501,2020-08-02 23:59:28.137000+00:00,26,2020-08-02 23:30:00+00:00
3,2,33,2020-08-03,0,period_0_00,D,8110,2020-08-03 00:02:28.070000+00:00,2,2020-08-03 00:00:00+00:00
4,2,33,2020-08-03,0,period_0_00,D,11719,2020-08-03 00:05:28.204000+00:00,35,2020-08-03 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...
90933,33436,84529,2021-01-05,1,period_8_00,F,80439,2021-01-05 08:15:48.255000+00:00,1,2021-01-05 08:00:00+00:00
90934,33437,84533,2021-01-09,5,period_13_30,F,81563,2021-01-09 13:36:02.300000+00:00,2,2021-01-09 13:30:00+00:00
90935,33438,84533,2021-04-22,3,period_5_00,F,90430,2021-04-22 05:11:07.314000+00:00,9,2021-04-22 05:00:00+00:00
90936,33439,84534,2021-01-09,5,period_13_30,D,81560,2021-01-09 13:35:25.313000+00:00,24,2021-01-09 13:30:00+00:00
90937,33440,84535,2021-01-09,5,period_13_30,F,81561,2021-01-09 13:35:38.275000+00:00,9,2021-01-09 13:30:00+00:00